config/routes.rb
Rails.application.routes.draw do
  get 'cards/new'
  post 'cards/new' => 'cards#create'

  get 'cards/update'
  get 'cards/:id/edit' => 'cards#edit', as: :edit
  patch 'cards/:id/edit' => 'cards#update', as: :update
  get 'cards/destroy'

  root 'cards#index'

end

app/models/card.rb
class Card < ActiveRecord::Base

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def new
    @card = Card.new
  end

  def create
    @card = Card.new(card_params)
    if @card.save
       redirect_to root_path
    else
        render 'new'
    end
  end

  def edit
    @card_edit = Card.find(params[:id])
  end

  def update
    @card = Card.find(params[:id])
    if @card.update_attributes(card_params)
      redirect_to root_path
    end
  end

  def destroy
  end

  def index
    @card = Card.new
    @cards = Card.all
  end

  def show
  end



  private

      def card_params
          params.require(:card).permit(:link_to_ticket, :ticket_title, :migration, :rake_task, :other_prod_concern, :regression_concern, :regression_textbox,:ticket_notes, :status, :archived)
      end
end

app/helpers/application_helper.rb
module ApplicationHelper

  end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/create.html.erb
<h1>Cards#create</h1>
<p>Find me in app/views/cards/create.html.erb</p>

app/views/cards/destroy.html.erb
<h1>Cards#destroy</h1>
<p>Find me in app/views/cards/destroy.html.erb</p>

app/views/cards/edit.js.erb
$(".editor").html("<%= j render(partial: 'shared/editform') %>").fadeIn( 750 );

app/views/cards/index.html.erb
<div class="container">

  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#tickets" aria-controls="tickets" role="tab" data-toggle="tab">Tickets</a></li>
    <li role="presentation"><a href="#regression" aria-controls="regression" role="tab" data-toggle="tab">Regressions</a></li>
    <li role="presentation"><a href="#production" aria-controls="production" role="tab" data-toggle="tab">Production</a></li>
    <li role="presentation"><a href="#archived" aria-controls="archived" role="tab" data-toggle="tab">Archived</a></li>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane fade in active" id="tickets">
      <!-- Beginning of Square Grid-->
      <div class="row">
          <!--Buttons for Sorting-->
        <div id="filters" class="button-group">
          <button type="button" class="button is-checked" data-filter="*" data-toggle="tooltip" data-placement="bottom">show all</button>
          <button type="button" class="button" data-toggle="tooltip" data-placement="bottom" data-filter=".Working">Working</button>
          <button type="button" class="button" data-toggle="tooltip" data-placement="bottom" data-filter=".Blocked">Blocked</button>
          <button type="button" class="button" data-toggle="tooltip" data-placement="bottom" data-filter=".Completed">Completed</button>
          <div class="btn btn-info" data-toggle="modal" data-target="#newTicket">New Ticket</div>
        </div>
      </div>
      <div class="row isotope">
        <% @cards.where('archived =?', false).each do |card| %>
        <div class="col-md-3 col-xs-6 <%= card.status %>" data-toggle="modal" data-target="#editTicket<%= card.id %>">
          <div class="thumbnail ticketinfo gradient">
            <%= card.link_to_ticket %>
            <%= card.ticket_title %>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  <!--      End of Square Grid-->
    <div role="tabpanel" class="tab-pane fade" id="regression">
        <% @cards.where('regression_concern =? AND archived =?', true,false).each do |card| %>
          <div class="col-md-3 col-xs-6" data-toggle="modal" data-target="#editTicket<%= card.id %>">
            <div class="thumbnail ticketinfo gradient">
              <%= card.link_to_ticket %>
              <%= card.ticket_title %>
            </div>
          </div>
        <% end %>
    </div>
    <div role="tabpanel" class="tab-pane fade" id="production">
      <% @cards.where('rake_task=? OR migration=?', true, true).where('archived =?', false).each do |card| %>
        <div class="col-md-3 col-xs-6" data-toggle="modal" data-target="#editTicket<%= card.id %>">
          <div class="thumbnail ticketinfo gradient">
            <%= card.link_to_ticket %>
            <%= card.ticket_title %>
          </div>
        </div>
      <% end %>
    </div>
    <div role="tabpanel" class="tab-pane fade" id="archived">
      <% @cards.where('archived =?', true).each do |card| %>
        <div class="col-md-3 col-xs-6" data-toggle="modal" data-target="#editTicket<%= card.id %>">
          <div class="thumbnail ticketinfo gradient">
            <%= card.link_to_ticket %>
            <%= card.ticket_title %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<!-- Modal -->
<% @cards.each do |card| %>
  <div class="modal fade" id="editTicket<%= card.id %>" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title"><%= card.link_to_ticket %> <%= card.ticket_title %></h4>
        </div>
        <div class="modal-body editor">
          <div class="row">
            <div class="col-md-12 col-xs-12"><h4>Ticket Notes : <%= card.status %></h4></div>
            <div class="col-md-12"><%= simple_format card.ticket_notes %></div>
            <div class=col-md-12><h4>Production Notes</h4></div>
            <div class=col-md-6>Rake Task: <%= card.rake_task %></div>
            <div class=col-md-6>Migration: <%= card.migration %></div>
            <div class="col-md-12"><%= simple_format card.other_prod_concern %></div>
            <div class=col-md-12><h4>Regression Notes</h4></div>
            <div class="col-md-12"><%= simple_format card.regression_textbox %></div>
            <div class="col-md-3 col-xs-4 pull-right">
              <%= link_to "Edit", edit_path(card), :class => 'btn btn-primary', :remote => true %>
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
          </div>

        </div>
      </div>
    </div>
  </div>
  <% end %>

<!-- New Ticket Modal -->
  <div class="modal fade" id="newTicket" role="dialog">
    <div class="modal-dialog">
      <!-- New ticket modal -->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">New Ticket</h4>
        </div>
        <div class="modal-body">
          <%= render 'shared/cardform' %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>

app/views/cards/index.js.erb
$( ".btn-default" ).on( "click", function(e) {
  e.preventDefault();
  $('.editor').html("<%= j render(partial: 'shared/showCardModal') %>");
  });

app/views/cards/new.html.erb
<h1>Cards#new</h1>
<p>Find me in app/views/cards/new.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tickets</title>
  <script type="text/javascript">
        window.module = undefined;
        window.require = undefined;
  </script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://npmcdn.com/isotope-layout@3.0/dist/isotope.pkgd.min.js"></script>
  <%= csrf_meta_tags %>
  <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">

</head>
<body>

<%= yield %>

</body>
</html>

app/views/shared/_cardform.html.erb
<%= form_for(@card, url: cards_new_path) do |f| %>
  <%= f.number_field :link_to_ticket %>
  <%= f.text_field :ticket_title %>
  <%= f.check_box(:migration) %>
  <%= f.label(:migration, "Migration") %>
  <%= f.check_box(:rake_task) %>
  <%= f.label(:rake_task, "Rake Task") %>
  <%= f.text_field :other_prod_concern %>
  <%= f.check_box(:regression_concern) %>
  <%= f.label(:regression_concern, "Regression Concern") %>
  <%= f.text_field :regression_textbox %>
  <%= f.text_field :ticket_notes %>
  <%= f.select(:status, ['Working', 'Blocked', 'Completed']) %>
  <%= f.check_box(:archived) %>
  <%= f.label(:archived, "Archive") %>
  <%= f.submit "Sign up", class:"form-control btn btn-register" %>
<% end %>

app/views/shared/_editform.html.erb
<div class="row">
  <%= form_for(@card_edit, remote: true, url: edit_path) do |f| %>
    <div class="col-md-4 col-xs-4"><%= f.number_field :link_to_ticket %></div>
    <div class="col-md-4 col-xs-4"><%= f.text_field :ticket_title %></div>
    <div class="col-md-4 col-xs-4"><%= f.select(:status, ['Working', 'Blocked', 'Completed']) %></div>
    <div class="col-md-12 col-xs-12"><h4>Ticket Notes</h4></div>
    <div class="col-md-12 col-xs-12"><%= f.text_area :ticket_notes %></div>
    <div class="col-md-12 col-xs-12"><h4>Production Notes</h4></div>
    <div class="col-md-12 col-xs-12"><%= f.text_area :other_prod_concern %></div>
    <div class="col-md-12 col-xs-12"><h4>Regression Notes</h4></div>
    <div class="col-md-12 col-xs-12"><%= f.text_area :regression_textbox %></div>
    <div class="col-md-3 col-xs-3">Rake Task: <%= f.check_box(:rake_task) %></div>
    <div class="col-md-3 col-xs-3">Migration: <%= f.check_box(:migration) %></div>
    <div class="col-md-3 col-xs-3">Regression:<%= f.check_box(:regression_concern) %></div>
    <div class="col-md-3 col-xs-3">Archive: <%= f.check_box(:archived) %></div>
    <div class="col-md-4 col-xs-4 pull-right">
      <%= f.submit "Update", class:"btn btn-danger" %>
  <% end %>
      <button type="button" class="btn btn-defaul" data-dismiss="modal">Close</button>
    </div>
</div>

app/views/shared/_showCardModal.html.erb
  <%= @cards.link_to_ticket %>